# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisteration',
            name='user',
        ),
        migrations.AddField(
            model_name='userregisteration',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
