# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solarapp', '0002_auto_20181014_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisteration',
            name='username',
        ),
        migrations.AddField(
            model_name='userregisteration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
