# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0004_auto_20181014_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
